theme: jekyll-theme-minimal
title: My IT Profile
description: COSC2196 Introduction to Information Technology; Assignment 1
description:<a href="IdealJob.html">Ideal Job</a>
description:<a href="PersonalProfile.html">Personal Profile</a>
description:<a href="ProjectIdea.html">Project Idea</a>
logo: ProfileImage.jpg